/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eindwerkjava;

import DAL.*;
import Services.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jo
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form UserFrame
     */
    Save save = new Save();
    GetList getList = new GetList();
    Delete delete = new Delete();
    Find find = new Find();
    Update update = new Update();
    ArrayList<String> namen = new ArrayList<>();
    boolean edit = false;
    
    public UserFrame() {
        initComponents();
        RefreshList();
        btnSave.setVisible(false);
        btnCancel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGebuikers = new javax.swing.JList();
        ckbAdmin = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnTerug = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtWachtwoord = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        txtZoek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lstGebuikers.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstGebuikers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGebuikersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstGebuikers);

        ckbAdmin.setText("Admin");
        ckbAdmin.setEnabled(false);

        jLabel1.setText("UserName:");

        txtUser.setEnabled(false);
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit User");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnNew.setText("New User");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnDel.setText("delete User");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnTerug.setText("Return");
        btnTerug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerugActionPerformed(evt);
            }
        });

        jLabel2.setText("Password:");

        txtWachtwoord.setEnabled(false);

        btnSave.setText("save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel4.setText("Id:");

        txtId.setEnabled(false);

        btnCancel.setText("cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel5.setText("Search:");

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTerug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtZoek, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(ckbAdmin)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtId)
                            .addComponent(txtUser)
                            .addComponent(txtWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ckbAdmin)
                            .addComponent(btnSave)
                            .addComponent(btnCancel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnNew)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel)
                        .addGap(18, 18, 18)
                        .addComponent(btnTerug)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZoek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton1))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(lstGebuikers.getSelectedIndex() != -1)
        {
            EnableText();
            DisableButton();
            edit = true;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No items selected");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        EnableText();
        DisableButton();
        txtId.setText("");
        txtUser.setText("");
        txtWachtwoord.setText("");
        ckbAdmin.setSelected(false);
        edit = false;
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        if(lstGebuikers.getSelectedIndex() !=  -1)
        {
            delete.DeleteAccount(Integer.parseInt(txtId.getText()));
            txtId.setText("");
            txtUser.setText("");
            txtWachtwoord.setText("");
            ckbAdmin.setSelected(false);
            RefreshList();
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnTerugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerugActionPerformed
        new MainFrame().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTerugActionPerformed

    private void lstGebuikersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGebuikersValueChanged
        SetTextbox();
    }//GEN-LAST:event_lstGebuikersValueChanged

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try
        {
            if(edit == true)
            {
                Account a = new Account();
                if(ckbAdmin.isSelected()==true)a.setAdmin(true);
                else a.setAdmin(false);
                a.setId(Long.parseLong(txtId.getText()));
                a.setNaam(txtUser.getText());
                a.setWachtwoord(txtWachtwoord.getText());
                int result = update.UpdateAccount(a);
                if(result == 1)JOptionPane.showMessageDialog(null, "Update done");
                else if(result == 2) JOptionPane.showMessageDialog(null, "Update failed, Item alreadt exists");
                else JOptionPane.showMessageDialog(null, "update failed");
            }
            else if(edit == false)
            {
                Account a = new Account();
                if(ckbAdmin.isSelected()==true)a.setAdmin(true);
                else a.setAdmin(false);
                a.setNaam(txtUser.getText());
                a.setWachtwoord(txtWachtwoord.getText());
                int result = save.saveAccount(a);
                if(result == 1)
                {
                    JOptionPane.showMessageDialog(null, "There was a error while saving" );
                }
                else if(result == 2)
                {
                   JOptionPane.showMessageDialog(null, "Item already exist");
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Saved");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Vreemde error, jo check dit");
            }
        DisableText();
        EnableButton();       
        RefreshList();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        DisableText();
        EnableButton();
        SetTextbox();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try
        {
            namen.clear();
            List<Account> AccountList = getList.AccountList();
            for(Account a: AccountList)
            {
                if(a.getNaam().toLowerCase().contains(txtZoek.getText().toLowerCase()))
                {
                namen.add(a.getNaam());
                }
            }
            lstGebuikers.setListData(namen.toArray());
            lstGebuikers.setSelectedIndex(0);
            SetTextbox();
        }
        catch(Exception ex){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

     private void RefreshList()
    {
        try
        {
            namen.clear();
            List<Account> AccountList = getList.AccountList();
            for(Account a: AccountList)
            {
                namen.add(a.getNaam());
            }
            lstGebuikers.setListData(namen.toArray());
            lstGebuikers.setSelectedIndex(0);
            SetTextbox();
        }
        catch(Exception ex){
            
        }
    }
     
     private void DisableButton()
     {
        btnDel.setVisible(false);
        btnEdit.setVisible(false);
        btnNew.setVisible(false);
        btnSave.setVisible(true);
        btnTerug.setVisible(false);
        btnCancel.setVisible(true);
     }
     
     private void EnableButton()
     {
        btnDel.setVisible(true);
        btnEdit.setVisible(true);
        btnNew.setVisible(true);
        btnSave.setVisible(false);
        btnTerug.setVisible(true);
        btnCancel.setVisible(false);
     }
     
     private void DisableText()
     {
        txtUser.setEnabled(false);
        txtWachtwoord.setEnabled(false);
        ckbAdmin.setEnabled(false);
        txtId.setText("");
        txtUser.setText("");
        txtWachtwoord.setText("");
        ckbAdmin.setSelected(false);
     }
     
     private void EnableText()
     {
        txtUser.setEnabled(true);
        txtWachtwoord.setEnabled(true);
        ckbAdmin.setEnabled(true);
     }
     
     private void SetTextbox()
     {
        if(lstGebuikers.getSelectedIndex() != -1)
        {
            Account result = find.findAccountByName(namen.get(lstGebuikers.getSelectedIndex()));
            txtUser.setText(result.getNaam());
            txtWachtwoord.setText(result.getWachtwoord());
            if(result.isAdmin() == true)ckbAdmin.setSelected(true);
            else ckbAdmin.setSelected(false);
            txtId.setText(Long.toString(result.getId()));
        }
     }
    
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTerug;
    private javax.swing.JCheckBox ckbAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstGebuikers;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtWachtwoord;
    private javax.swing.JTextField txtZoek;
    // End of variables declaration//GEN-END:variables
}
